server:
     port: 9001
spring:
     application:
       name: yuno-gateway #指定微服务的名称. 注意,英文字母之间只能用-,不能用下划线连接
     datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://111.231.79.149:3306/tensquare_base?characterEncoding=UTF8
       username: root
       password: Miku520@
     jpa:
       database: mysql  #数据库的类型为mysql
       show-sql: true   # 在控制台打印sql语句
